# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GinnS9OuA5gpOfMQiUp_tYmmeUai2gKN
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, RobustScaler

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
display(df)

#  Gender -> Label Encoding
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

# City -> One-Hot Encoding
df = pd.get_dummies(df, columns=['City'], drop_first=True)

#  Size -> Label Encoding (Ordinal)
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)

display(df)

scaler = RobustScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])
print(" dataframe:")
display(df)

